language: cpp

install:
  # Prerequisites
  - sudo apt-get install gobjc++

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

script:
  - cmake -Hsamples -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd build
  - make